// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CPPinInput struct {
	Title             string  `json:"title"`
	Description       *string `json:"description"`
	Filters           string  `json:"filters"`
	Context           string  `json:"context"`
	VisualizationFlag *bool   `json:"visualization_flag"`
	WorkbookID        string  `json:"workbookID"`
}
